const BAD_REQUEST = 400
const UNAUTHORIZED = 401
const UNAUTHORIZED_USER = 403
const NOT_FOUND = 404
const CONFLICT_ERROR = 409
const SERVER_ERROR = 500

module.exports = { BAD_REQUEST, UNAUTHORIZED, UNAUTHORIZED_USER, NOT_FOUND, SERVER_ERROR, CONFLICT_ERROR }